name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Load environment variables from .env
        run: |
          # Read .env file and export variables
          set -a
          source .env
          set +a
          
          # Set GitHub environment variables
          echo "VERCEL_TOKEN=$VERCEL_TOKEN" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=$VERCEL_ORG_ID" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID" >> $GITHUB_ENV
          
          # Debug: Check if variables are set (without exposing values)
          echo "VERCEL_TOKEN is set: $([ -n "$VERCEL_TOKEN" ] && echo "YES" || echo "NO")"
          echo "VERCEL_ORG_ID is set: $([ -n "$VERCEL_ORG_ID" ] && echo "YES" || echo "NO")"
          echo "VERCEL_PROJECT_ID is set: $([ -n "$VERCEL_PROJECT_ID" ] && echo "YES" || echo "NO")"
          
          # Show the first few characters of each variable for debugging
          echo "VERCEL_TOKEN starts with: ${VERCEL_TOKEN:0:4}..."
          echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"

      - name: Lint
        run: yarn lint || yarn run lint

      - name: Run Unit Tests
        run: yarn test:unit || yarn run test:unit

      - name: Install system dependencies for Playwright
        run: npx playwright install-deps

      - name: Install Playwright Browsers
        run: yarn playwright install

      - name: Build
        run: yarn build

      - name: Start Next.js server
        run: yarn start &

      - name: Wait for Next.js to be ready
        run: npx wait-on http://localhost:3000

      # (Optional) Run Playwright E2E tests after server is ready
      # - name: Run E2E Tests
      #   run: yarn test:e2e

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ env.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}
        if: env.VERCEL_TOKEN != ''
